app/Controllers/CountriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
using app.Models;

namespace app.Controllers
{
    public class CountriesController : Controller
    {
        private DatabaseEntities db = new DatabaseEntities();

        //return list of all countries
        public ActionResult Index()
        {
            return View(db.Countries.ToList());
        }

        //return all info(from differents tables) about country by id
        public ActionResult ShowCountry(int id)
        {
            return View(db.Countries.Find(id)); 
        }
    }
}

app/Controllers/TestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
using System.Net;
using app.Models;

namespace app.Controllers
{
    public class TestsController : Controller
    {
        private DatabaseEntities db = new DatabaseEntities();

        //show test's types
        public ActionResult Index()
        {
            return View(db.TestTypes.ToList());
        }

        //show questions in one type
        //public ActionResult PassTest(int id)
        //{
        //    ViewBag.Header = db.TestTypes.Find(id).Type;

        //    IList<QuestionsViewModel> model = new List<QuestionsViewModel> ();
        //    IEnumerable<Question> questionmy;

        //    int quantity = db.Questions.Count();
        //    Random r = new Random();
        //    int[] arr = new int[5];

        //    Question quest = null;

        //    for (int i=1; i<=arr.Length; i++)
        //    {
        //        int rand = r.Next(1, quantity+1);
        //        if(arr.Contains(rand))
        //        {
        //            i--;
        //            continue;
        //        }
        //        quest = db.Questions.Find(rand);
        //        if(quest.TestTypes_Id != id)
        //        {
        //            i--;
        //            continue;
        //        }
        //        arr[i - 1] = rand;
        //        Question q = null;
        //        List<Answer> a = new List<Answer> ();

        //        if (quest.TestTypes_Id == id)
        //        {
        //            q = quest;
        //            foreach(var j in db.Answers)
        //            {
        //                if(j.Questions_Id == quest.Id)
        //                {
        //                    a.Add(j);
        //                }

        //            }
        //            model.Add(new QuestionsViewModel()
        //            {
        //                Question = q,
        //                Answers = a
        //            });
        //        }
        //    }
        //    if (id == 1)
        //        return View("PassTest", model);
        //    else
        //        return View("~/Views/Tests/PassTest_Img.cshtml", model);
        //}

        public ActionResult PassTest(int id)
        {
            ViewBag.Header = db.TestTypes.Find(id).Type;

            List<Question> listquestions = new List<Question>();
            Question quest = null;

            int quantity = db.Questions.Count();
            Random r = new Random();
            int[] arr = new int[5];

            for (int i = 1; i <= arr.Length; i++) //find 5 appropriated questions
            {
                int rand = r.Next(1, quantity + 1);
                if (arr.Contains(rand))
                {
                    i--;
                    continue;
                }
                quest = db.Questions.Find(rand);
                if (quest.TestTypes_Id != id) //id questions are repeated, search new question
                {
                    i--;
                    continue;
                }
                arr[i - 1] = rand;
                listquestions.Add(quest); //add appropriated questions
            }
            if (id == 1)
                return View("PassTest", listquestions);
            else
                return View("~/Views/Tests/PassTest_Img.cshtml", listquestions);
        }

        //show a right answer
        public PartialViewResult AjaxCheckAnswer(int id)
        {
            int idQuestion = db.Answers.Find(id).Questions_Id;

            //QuestionsViewModel model = new QuestionsViewModel()
            //{
            //    Questions = (Question)db.Questions.Find(idQuestion),
            //    Answers = (IList<Answer>)db.Answers.Where(i => i.Questions_Id == idQuestion)
            //};

            List<Answer> newlist = new List<Answer>();
            foreach (var i in db.Answers.Where(i => i.Questions_Id == idQuestion))
            {
                newlist.Add(i);
            }

            if (db.Answers.Find(id).Right == true)
            {
                ViewBag.WrongAns = null;
            }
            else
            {
                ViewBag.WrongAns = db.Answers.Find(id);
            }

            if(db.Questions.Find(idQuestion).TestTypes_Id == 1)
                return PartialView("_PartialView_Answers", newlist);
            else
                return PartialView("_PartialView_Answers_Img", newlist);
        }
    }
}

app/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Around The World</title>

    @Styles.Render("~/Content/css")
    


    @*<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />*@
    @*<link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />*@
    @*<script src="~/Scripts/modernizr-2.6.2.js"></script>*@

    
</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Around the World", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Главная", "Index", "Home")</li>
                    <li>@Html.ActionLink("Страны", "Index", "Countries")</li>
                    <li>@Html.ActionLink("Онлайн-тесты", "Index", "Tests")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="body-content">

        @RenderBody()

        <!--<hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>-->
    </div>



    
    @*<script src='@Scripts.Url("~/bundles/jquery")' async> </script>*@
    @*@RenderSection("jquery", required: true)*@
    
     
    @*@RenderSection("scripts", required: false)*@

    <!--<script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/mansory_lib.js"></script>
    <script src="~/Scripts/script.js"></script>-->

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @*@Scripts.Render("~/bundles/mansory")*@
    @*@Scripts.Render("~/bundles/ajaxjs")*@
    @RenderSection("Scripts", required: false)

</body>
</html>

app/Views/Shared/_PartialView_Answers.cshtml
@model List<app.Models.Answer>
@{
    ViewBag.Title = "PP";
}

@foreach (var i in Model)
{
    <li class="answ_li col-xs-12 col-sm-4 col-md-3 col-lg-2">
            @if (@i.Right == true)
            {
                <div class="qestion__btn col-xs-11" style="background:green;margin:0px;">@i.Text</div>
            }
            else if (@i == ViewBag.WrongAns)
            {
                <div class="qestion__btn col-xs-11" style="background:red;margin:0px;">@i.Text</div>
            }
            else
            {
                <div class="qestion__btn col-xs-11" style="margin:0px;">@i.Text</div>
            }
    </li>
}

app/Views/Shared/_PartialView_Answers_Img.cshtml
@model List<app.Models.Answer>
@{
    ViewBag.Title = "PP";
}

@foreach (var i in Model)
{
    <li class="answ_li col-xs-12">
            @if (@i.Right == true)
            {
                <div class="qestion__btn col-xs-6" style="background:green;margin:0px;">@i.Text</div>
            }
            else if (@i == ViewBag.WrongAns)
            {
                <div class="qestion__btn col-xs-6" style="background:red;margin:0px;">@i.Text</div>
            }
            else
            {
                <div class="qestion__btn col-xs-6" style="margin:0px;">@i.Text</div>
            }
    </li>
}